version: "3.2"

services:
  db:
    image: postgres:15
    container_name: cronjobs-db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/var/lib/postgresql/data

  app:
    build: .
    container_name: cronjobs-app
    restart: always
    env_file:
      - .env
    ports:
      - 5000:5000
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: cronjobs-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
